apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: production
spec:
  kind: Permanent
  label: Production
  namespace: gke-production
  order: 200
  previewGitInfo:
    user: {}
  promotionStrategy: Manual
  source:
    url: https://github.com/explore-jenkinsx/environment-jx-gke-production.git
  teamSettings:
    defaultScheduler:
      kind: ""
      name: ""
status: {}
